Repository janosh/svelte-multiselect, pull requests merged in 2023-06, with the labels that each got.

#236 Fix [svelte-check] Cannot find module 'svelte-multiselect' or its corresponding type declarations
  package.json
Labels: DX, types, pkg

#238 Rename prop `duplicateFunc()` to `key()`
  package.json
  readme.md
  src/app.css
  src/lib/CmdPalette.svelte
  src/lib/MultiSelect.svelte
  src/routes/(demos)/allow-user-options/+page.svx
  src/routes/(demos)/duplicates/+page.md
  tests/MultiSelect.test.ts
  tests/unit/MultiSelect.test.ts
Labels: fix, breaking

#240 Add `<slot name="user-msg">`
  .pre-commit-config.yaml
  package.json
  readme.md
  src/lib/MultiSelect.svelte
  src/routes/(demos)/slots/+page.svx
  tests/MultiSelect.test.ts
Labels: enhancement

#243 Add Multiselect prop `maxOptions: number`
  .github/workflows/gh-pages.yml
  readme.md
  src/lib/MultiSelect.svelte
  src/site/Examples.svx
  svelte.config.js
  tests/unit/MultiSelect.test.ts
Labels: enhancement
