Repository janosh/svelte-multiselect, pull requests merged in 2023-05, with the labels that each got.

#224 Fix `pnpm` install command
  readme.md
Labels: docs

#226 Fix MultiSelect unable to deselect object options
  src/lib/MultiSelect.svelte
  tests/unit/MultiSelect.test.ts
Labels: testing

#227 Allow `createOptionMsg=null` to suppress console error when `allowUserOptions` thruthy
  readme.md
  src/lib/MultiSelect.svelte
  src/routes/(demos)/allow-user-options/+page.svx
  tests/unit/MultiSelect.test.ts
Labels: enhancement, testing

#230 Remove circular import between `MultiSelect` and `index.ts`
  package.json
  src/lib/MultiSelect.svelte
  src/lib/index.ts
  src/lib/types.ts
Labels: refactor

#231 Add default slot
  .github/workflows/test.yml
  package.json
  readme.md
  src/app.html
  src/lib/CmdPalette.svelte
  src/lib/MultiSelect.svelte
  src/routes/(demos)/allow-user-options/+page.svx
  src/routes/(demos)/form/+page.svx
  src/routes/(demos)/kit-form-actions/+page.svx
  src/routes/(demos)/min-max-select/+page.svx
  src/routes/(demos)/slots/+page.svx
  src/routes/(demos)/sort-selected/+page.svx
  src/site/Examples.svx
  svelte.config.js
  tests/unit/MultiSelect.test.ts
Labels: enhancement, DX

#232 Revert "Fix Svelte 3.57 a11y (#215)"
  readme.md
  src/lib/MultiSelect.svelte
  src/routes/(demos)/ui/+page.svx
  tests/MultiSelect.test.ts
  tests/unit/CmdPalette.test.ts
Labels: testing, a11y
