Repository janosh/svelte-multiselect, pull requests merged in 2023-03, with the labels that each got.

#210 Fix Lighthouse a11y issues
  readme.md
  src/lib/MultiSelect.svelte
  src/routes/(demos)/disabled/+page.svx
  tests/MultiSelect.test.ts
  tests/unit/CmdPalette.test.ts
  tests/unit/MultiSelect.test.ts
Labels: a11y

#211 fix: add missing role attr for <li>
  src/lib/MultiSelect.svelte
Labels: a11y

#212 Add prop `highlightMatches` to `MultiSelect`
  package.json
  readme.md
  src/lib/MultiSelect.svelte
  src/lib/index.ts
  src/routes/(demos)/kit-form-actions/+page.svx
  src/routes/+layout.ts
  static/prism-vsc-dark-plus.css
  tests/unit/MultiSelect.test.ts
  tests/unit/Test2WayBind.svelte
Labels: enhancement

#215 Fix Svelte 3.57 a11y
  .github/workflows/gh-pages.yml
  .github/workflows/test.yml
  contributing.md
  package.json
  src/lib/MultiSelect.svelte
  src/routes/(demos)/ui/+page.svx
  svelte.config.js
  tests/MultiSelect.test.ts
Labels: a11y

#217 fix: allow object options to share the same label
  src/lib/MultiSelect.svelte
  tests/unit/MultiSelect.test.ts
Labels: testing, discussion
