Repository janosh/svelte-multiselect, pull requests merged in 2025-05, with the labels that each got.

#304 Prevent empty style attributes on `ul.selected > li` and `ul.options > li`
  .pre-commit-config.yaml
  src/lib/MultiSelect.svelte
  tests/unit/MultiSelect.svelte.test.ts
Labels: testing, dx

#306 Multiselect portal
  .pre-commit-config.yaml
  package.json
  readme.md
  src/app.css
  src/lib/CmdPalette.svelte
  src/lib/MultiSelect.svelte
  src/lib/Wiggle.svelte
  src/lib/props.ts
  src/routes/(demos)/+layout.svelte
  src/routes/(demos)/modal/+page.svelte
  src/routes/+layout.svelte
  tests/MultiSelect.test.ts
  tests/unit/CmdPalette.svelte.test.ts
  vite.config.ts
Labels: enhancement

#308 Fix Rollup failed to resolve import `$app/environment`
  .github/workflows/link-check-config.json
  package.json
  src/lib/MultiSelect.svelte
  tests/MultiSelect.test.ts
Labels: tests, fix
